@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.aeromancy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;