@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.aeromancy.spells.summon_breeze;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;